$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model_custom
display_name: Train Model (Custom Invoker)
version: "SET_BY_GITHUB_ACTIONS"
type: command

inputs:
  Untrained_model:
    type: uri_folder
    description: Untrained learner
  Dataset:
    type: uri_folder
    description: Training data
  Label_column:
    type: string
    description: Select the column that contains the label or outcome column
  Model_explanations:
    type: boolean
    default: false
    optional: true

outputs:
  Trained_model:
    type: uri_folder
    description: Trained learner

code: ../../
environment: azureml:AzureML-Designer:89

command: >-
  python -m aml_shared.urldecode
  python -m azureml.studio.modules.ml.train.train_generic_model.train_generic_model
  --untrained-model ${{inputs.Untrained_model}}
  --dataset ${{inputs.Dataset}}
  --label-column "${{inputs.Label_column}}"
  $[[--model-explanations ${{inputs.Model_explanations}}]]
  --trained-model ${{outputs.Trained_model}}