$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: AppReview_EndToEnd_Pipeline
settings:
  default_compute: azureml:github-cluster

jobs:
  # 1. Text Preprocessing
  cleaning_step:
    type: command
    component: azureml:preprocess_text_custom:VERSION_PLACEHOLDER
    inputs:
      Dataset:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/UI/2026-04-22_015700_UTC/
      Text_column_to_clean: '{\"columnName\":\"reviewText\"}'
      Language: "English"
    outputs:
      Results_dataset:
        mode: upload

  # 2. Data Splitting (Train/Test)
  split_step:
    type: command
    component: azureml:split_data_custom:VERSION_PLACEHOLDER
    inputs:
      Dataset: ${{parent.jobs.cleaning_step.outputs.Results_dataset}}
      Fraction_of_rows_in_the_first_output_dataset: 0.8
      Randomized_split: true
      Random_seed: 42
    outputs:
      Results_dataset1:
        mode: upload
      Results_dataset2:
        mode: upload

  # 3. Model Initialization (Linear Regression)
  init_model_step:
    type: command
    component: azureml:linear_regression_custom:VERSION_PLACEHOLDER
    inputs:
      Solution_method: "Ordinary Least Squares"
      L2_regularization_weight: 0.005
    outputs:
      Untrained_model:
        mode: upload

  # 4. Model Training
  train_step:
    type: command
    component: azureml:train_model_custom:VERSION_PLACEHOLDER
    inputs:
      Untrained_model: ${{parent.jobs.init_model_step.outputs.Untrained_model}}
      Dataset: ${{parent.jobs.split_step.outputs.Results_dataset1}} # Using the 80% split
      Label_column: "reviewerRating" # Replace with your target column name
    outputs:
      Trained_model:
        mode: upload

  # 5. Model Scoring (Prediction)
  score_step:
    type: command
    component: azureml:score_model_custom:VERSION_PLACEHOLDER
    inputs:
      Trained_model: ${{parent.jobs.train_step.outputs.Trained_model}}
      Dataset: ${{parent.jobs.split_step.outputs.Results_dataset2}} # Using the 20% split
      Append_score_columns_to_output: true
    outputs:
      Scored_dataset:
        mode: upload
