$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: AppReview_Preprocess_Run

settings:
  default_compute: azureml:dsc592s26groupb-lite

jobs:
  cleaning_step:
    type: command
    component: azureml:preprocess_text_custom:1.0.1.1
    inputs:
      Dataset:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/UI/2026-04-22_015700_UTC/
      Text_column_to_clean: "reviewText" # Ensure this matches the header in your CSV
      Language: "English"
    outputs:
      Results_dataset:
        mode: upload
